name: Check Sub

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  Run_Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
          
      - name: Building Go Environment
        run: |
          go mod tidy
          mkdir output
          touch output/once

      - name: Setting config.yaml
        run: |
          cp ./config/config.example.yaml ./config/config.yaml
          # 设置最低保留测速结果
          sed -i 's/min-speed: 512/min-speed: 10240/' ./config/config.yaml
          sed -i 's/download-mb: 10/download-mb: 20/' ./config/config.yaml

      - name: Run Go
        run: |
          go run . -f ./config/config.yaml
          
      # - name: Release
      #   uses: goreleaser/goreleaser-action@v4
      #   with:
      #     distribution: goreleaser
      #     version: latest
      #     args: release --clean
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

